package com.example.supplychain;
import java.sql.*;
public class DatabaseConnection  {
    //these are essential three things for connecting the
    //database --> USR of database , userName ans PassWord for the username
    //              of the database
    private static final String DB_URL = "jdbc:mysql://localhost:3306/suppy_chain";
    private static final String USER = "root";
    private static final String PASS = "root";

    /*
    * The object used for executing a static SQL statement and returning
    * the results it produces.
    * By default, only one ResultSet object per Statement object
    * can be open at the same time. Therefore, if the reading of one
    * ResultSet object is interleaved with the reading of another,
    * each must have been generated by different Statement objects.
    * All execution methods in the Statement interface implicitly
    * close a current ResultSet object of the statement if an open one exists
    * */
    public Statement getStatement(){
        Statement statement = null;
        Connection conn;
        try{
            conn = DriverManager.getConnection(DB_URL,USER,PASS);
            statement = conn.createStatement();
        }catch(Exception e){
            e.printStackTrace();
        }
        return statement;
    }
    public ResultSet getQueryTable(String query){
        Statement statement = getStatement();
        try {
            return statement.executeQuery(query);
        }catch (Exception e){
            e.printStackTrace();
        }
        return null;
    }

    public int insertData(String query){
        Statement statement = getStatement();
        try {
            return statement.executeUpdate(query);
        }catch (Exception e){
            e.printStackTrace();
        }
        return 0;
    }


//    public static void main(String[] args){
//        DatabaseConnection dbconn = new DatabaseConnection();
//        String query = "SELECT * FROM customer";
//        ResultSet rs = dbconn.getQueryTable(query);
//        try {
//            while(rs != null && rs.next()){
//                System.out.println("Fetched Result");
//                System.out.println("id: "+rs.getInt("id")+" name: "+
//                        rs.getString("first_name") + " email: "+
//                        rs.getString("email"));
//            }
//        }catch (Exception e){
//            e.printStackTrace();
//        }
//    }
}
